export const ASEAN_MEMBER = {
  Countries: [
    'Singapore',
    'Brunei Darussalam',
    'Malaysia',
    'Thailand',
    'Indonesia',
    'Philippines',
    'Vietnam',
    'Laos',
    'Cambodia',
    'Myanmar',
  ],
  CountriesSlug: [
    'singapore',
    'brunei',
    'malaysia',
    'thailand',
    'indonesia',
    'philippines',
    'vietnam',
    'lao-pdr',
    'cambodia',
    'myanmar',
  ],
  CountriesCode: ['SG', 'BN', 'MY', 'TH', 'ID', 'PH', 'VN', 'LA', 'KH', 'MM'],
}
